import { useAppStore } from "../store";

export const useTeacher = () => {
  const {
    loadingTeacherApi,
    teacher_account,
    registerTeacher,
    applyTeach,
    createCourse,
    editCourse,
    removeCourse,
    myCourses,
    getApplicationTeach,
    application,
    profile,
    getProfile,
    _updateProfile,
    createAchievement,
    getCourse,
    currentCourse,
    wallet,
    _sendCourseToReview,
    _getWallet,
    _getClassrooms,
    _getCourses,
    _getTeacherCourse,
    _getMeetingRoomId,
    _validateMeetingRoomId,
    _makeWithdrawal,
    _updateApplicationTeach,
    _getQuizReview,
    _changeTeacherCommission
  } = useAppStore();

  return {
    loadingTeacherApi,
    course: currentCourse,
    teacher_account,
    registerTeacher,
    applyTeach,
    createCourse,
    editCourse,
    removeCourse,
    myCourses,
    getApplicationTeach,
    application,
    profile,
    getProfile,
    _updateProfile,
    createAchievement,
    getCourse,
    wallet,
    _sendCourseToReview,
    _getWallet,
    _getClassrooms,
    _getCourses,
    _getTeacherCourse,
    _getMeetingRoomId,
    _validateMeetingRoomId,
    _makeWithdrawal,
    _updateApplicationTeach,
    _getQuizReview,
    _changeTeacherCommission,
  }
}
