export * from './checkout/checkout';
export * from './home/home';
export * from './login/login';
export * from './register/register';
export * from './shopping-cart/shopping-cart';
export * from './checkout/checkout';
export * from './all-courses/all-courses';
export * from './course-details/course-details';
export * from './register-teacher/register-teacher';
